[build]
command = "curl -sS https://getcomposer.org/installer | php && php composer.phar install && php composer.phar update && npm run build"
publish = "public"

[build.environment]
PHP_VERSION = "8.1"
